import { NextResponse } from 'next/server'
import PropertyBlog from '@/models/PropertyBlog'
import connectDB from '@/lib/mongodb'

export async function GET(request: Request) {
  try {
    await connectDB()
    
    const { searchParams } = new URL(request.url)
    const limit = searchParams.get('limit')
    const sort = searchParams.get('sort') || 'createdAt:desc'
    
    // Parse sort parameter (format: field:direction)
    const [sortField, sortDirection] = sort.split(':')
    const sortObject: Record<string, 1 | -1> = { [sortField]: sortDirection === 'desc' ? -1 : 1 }
    
    let query = PropertyBlog.find()
      .sort(sortObject)
      .select('name slug hero_image sub_images content createdAt updatedAt')
      .lean()
    
    // Apply limit if specified
    if (limit) {
      const limitNum = parseInt(limit, 10)
      if (limitNum > 0) {
        query = query.limit(limitNum)
      }
    }
    
    const propertyPosts = await query.exec()

    return NextResponse.json(propertyPosts)
  } catch (error) {
    console.error('Error fetching property posts:', error)
    return NextResponse.json(
      { error: 'Failed to fetch property posts' },
      { status: 500 }
    )
  }
}

export async function POST(request: Request) {
  try {
    const body = await request.json()
    const { name, content, hero_image, sub_images } = body

    await connectDB()
    
    // Create the property post - the slug will be automatically generated by the pre-save middleware
    const propertyPost = await PropertyBlog.create({
      name,
      content,
      hero_image,
      sub_images: sub_images || [],
      createdAt: new Date(),
      updatedAt: new Date()
    })

    return NextResponse.json(propertyPost)
  } catch (error: any) {
    console.error('Error creating property post:', error)
    
    // Handle duplicate key error specifically
    if (error.code === 11000) {
      return NextResponse.json(
        { error: 'A property post with this name already exists. Please use a different name.' },
        { status: 400 }
      )
    }
    
    return NextResponse.json(
      { error: 'Failed to create property post' },
      { status: 500 }
    )
  }
}

export async function PUT(request: Request) {
  try {
    const body = await request.json()
    const { id, name, content, hero_image, sub_images } = body

    await connectDB()
    
    // Find the property post first to trigger the pre-save middleware for slug generation
    const propertyPost = await PropertyBlog.findById(id)
    if (!propertyPost) {
      return NextResponse.json(
        { error: 'Property post not found' },
        { status: 404 }
      )
    }
    
    // Update the property post fields
    propertyPost.name = name
    propertyPost.content = content
    propertyPost.hero_image = hero_image
    propertyPost.sub_images = sub_images || []
    propertyPost.updatedAt = new Date()
    
    // Save the property post (this will trigger slug regeneration if name changed)
    await propertyPost.save()

    return NextResponse.json(propertyPost)
  } catch (error: any) {
    console.error('Error updating property post:', error)
    
    // Handle duplicate key error specifically
    if (error.code === 11000) {
      return NextResponse.json(
        { error: 'A property post with this name already exists. Please use a different name.' },
        { status: 400 }
      )
    }
    
    return NextResponse.json(
      { error: 'Failed to update property post' },
      { status: 500 }
    )
  }
} 