import { NextResponse } from 'next/server'
import Post from '@/models/Post'
import User from '@/models/User'
import Category from '@/models/Category'
import connectDB from '@/lib/mongodb'

export async function GET(request: Request) {
  try {
    await connectDB()
    
    const { searchParams } = new URL(request.url)
    const limit = searchParams.get('limit')
    const sort = searchParams.get('sort') || 'createdAt:desc'
    
    // Parse sort parameter (format: field:direction)
    const [sortField, sortDirection] = sort.split(':')
    const sortObject: Record<string, 1 | -1> = { [sortField]: sortDirection === 'desc' ? -1 : 1 }
    
    let query = Post.find()
      .sort(sortObject)
      .select('title slug content metadata category coverImage createdAt updatedAt readTime')
      .lean()
    
    // Apply limit if specified
    if (limit) {
      const limitNum = parseInt(limit, 10)
      if (limitNum > 0) {
        query = query.limit(limitNum)
      }
    }
    
    const posts = await query.exec()

    return NextResponse.json(posts)
  } catch (error) {
    console.error('Error fetching posts:', error)
    return NextResponse.json(
      { error: 'Failed to fetch posts' },
      { status: 500 }
    )
  }
}

export async function POST(request: Request) {
  try {
    const body = await request.json()
    const { title, content, metadata, category, readTime, coverImage } = body

    await connectDB()
    
    // Create the post - the slug will be automatically generated by the pre-save middleware
    const post = await Post.create({
      title,
      content,
      metadata,
      category,
      readTime,
      coverImage,
      createdAt: new Date(),
      updatedAt: new Date()
    })

    // Update category to include this post if category exists
    if (category) {
      const categoryDoc = await Category.findOne({ name: category })
      if (categoryDoc && !categoryDoc.post_ids.includes(post._id)) {
        categoryDoc.post_ids.push(post._id)
        await categoryDoc.save()
      }
    }

    return NextResponse.json(post)
  } catch (error: any) {
    console.error('Error creating post:', error)
    
    // Handle duplicate key error specifically
    if (error.code === 11000) {
      return NextResponse.json(
        { error: 'A post with this title already exists. Please use a different title.' },
        { status: 400 }
      )
    }
    
    return NextResponse.json(
      { error: 'Failed to create post' },
      { status: 500 }
    )
  }
}

export async function PUT(request: Request) {
  try {
    const body = await request.json()
    const { id, title, content, metadata, category, readTime, coverImage } = body

    await connectDB()
    
    // Find the post first to trigger the pre-save middleware for slug generation
    const post = await Post.findById(id)
    if (!post) {
      return NextResponse.json(
        { error: 'Post not found' },
        { status: 404 }
      )
    }
    
    const oldCategory = post.category
    
    // Update the post fields
    post.title = title
    post.content = content
    post.metadata = metadata
    post.category = category
    post.readTime = readTime
    post.coverImage = coverImage
    post.updatedAt = new Date()
    
    // Save the post (this will trigger slug regeneration if title changed)
    await post.save()

    // Handle category changes
    if (oldCategory !== category) {
      // Remove from old category
      if (oldCategory) {
        const oldCategoryDoc = await Category.findOne({ name: oldCategory })
        if (oldCategoryDoc) {
          oldCategoryDoc.post_ids = oldCategoryDoc.post_ids.filter(
            (postId: any) => postId.toString() !== id
          )
          await oldCategoryDoc.save()
        }
      }
      
      // Add to new category
      if (category) {
        const newCategoryDoc = await Category.findOne({ name: category })
        if (newCategoryDoc && !newCategoryDoc.post_ids.includes(post._id)) {
          newCategoryDoc.post_ids.push(post._id)
          await newCategoryDoc.save()
        }
      }
    }

    return NextResponse.json(post)
  } catch (error: any) {
    console.error('Error updating post:', error)
    
    // Handle duplicate key error specifically
    if (error.code === 11000) {
      return NextResponse.json(
        { error: 'A post with this title already exists. Please use a different title.' },
        { status: 400 }
      )
    }
    
    return NextResponse.json(
      { error: 'Failed to update post' },
      { status: 500 }
    )
  }
} 