import { NextResponse } from 'next/server'
import Post from '@/models/Post'
import User from '@/models/User'
import connectDB from '@/lib/mongodb'

export async function GET() {
  try {
    await connectDB()
    const posts = await Post.find()
      .sort({ createdAt: -1 })
      .lean()

    return NextResponse.json(posts)
  } catch (error) {
    console.error('Error fetching posts:', error)
    return NextResponse.json(
      { error: 'Failed to fetch posts' },
      { status: 500 }
    )
  }
}

export async function POST(request: Request) {
  try {
    const body = await request.json()
    const { title, content, excerpt, category, readTime } = body

    await connectDB()
    
    // Create the post - the slug will be automatically generated by the pre-save middleware
    const post = await Post.create({
      title,
      content,
      excerpt,
      category,
      readTime,
      createdAt: new Date(),
      updatedAt: new Date()
    })

    return NextResponse.json(post)
  } catch (error: any) {
    console.error('Error creating post:', error)
    
    // Handle duplicate key error specifically
    if (error.code === 11000) {
      return NextResponse.json(
        { error: 'A post with this title already exists. Please use a different title.' },
        { status: 400 }
      )
    }
    
    return NextResponse.json(
      { error: 'Failed to create post' },
      { status: 500 }
    )
  }
}

export async function PUT(request: Request) {
  try {
    const body = await request.json()
    const { id, title, content, excerpt, category, readTime } = body

    await connectDB()
    
    // Find the post first to trigger the pre-save middleware for slug generation
    const post = await Post.findById(id)
    if (!post) {
      return NextResponse.json(
        { error: 'Post not found' },
        { status: 404 }
      )
    }
    
    // Update the post fields
    post.title = title
    post.content = content
    post.excerpt = excerpt
    post.category = category
    post.readTime = readTime
    post.updatedAt = new Date()
    
    // Save the post (this will trigger slug regeneration if title changed)
    await post.save()

    return NextResponse.json(post)
  } catch (error: any) {
    console.error('Error updating post:', error)
    
    // Handle duplicate key error specifically
    if (error.code === 11000) {
      return NextResponse.json(
        { error: 'A post with this title already exists. Please use a different title.' },
        { status: 400 }
      )
    }
    
    return NextResponse.json(
      { error: 'Failed to update post' },
      { status: 500 }
    )
  }
} 